[package]
name = "ss3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
puremp3 = "0.1.0"
rodio = "0.17.1"
spectrum-analyzer = "1.4.0"



